Args = -H:ReflectionConfigurationResources=META-INF/native-image/yaac/reflect-config.json \
       -H:ResourceConfigurationResources=META-INF/native-image/yaac/resource-config.json \
       --features=clj_easy.graal_build_time.InitClojureClasses \
       -H:+UnlockExperimentalVMOptions \
       --initialize-at-build-time=org.fusesource.jansi,java.sql.Date,org.slf4j.impl.StaticLoggerBinder,com.github.fzakaria.slf4j.timbre \
       --enable-url-protocols=jar,http,https \
       -H:+AddAllCharsets \
       -H:+ReportExceptionStackTraces
