Args = -H:ReflectionConfigurationResources=META-INF/native-image/silvur/reflect-config.json \
       -H:ResourceConfigurationResources=META-INF/native-image/silvur/resource-config.json \
       --enable-url-protocols=https \
       -H:+AddAllCharsets
